service: messaging-api

custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    current: ${ternary( ${self:custom.env}, prod, ${self:custom.vpcSettings.prod}, ~ )}

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}

functions:
  web:
    handler: LambdaEntry.handleWeb
    events:
      - http: ANY {proxy+}
      - http: ANY /
    vpc: ${self:custom.vpcSettings.current}
  socket:
    handler: LambdaEntry.handleSocket
    events:
      - websocket: $default
      - websocket: $disconnect
    vpc: ${self:custom.vpcSettings.current}
  timer15Min:
    handler: LambdaEntry.timer15Min
    events:
      - schedule: rate(15 minutes)
    vpc: ${self:custom.vpcSettings.current}
  timerMidnight:
    handler: LambdaEntry.timerMidnight
    events:
      - schedule: cron(0 5 * * ? *)
    vpc: ${self:custom.vpcSettings.current}

plugins:
  - serverless-layers
  - serverless-plugin-utils
