service: messaging-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${lower(${opt:stage, self:provider.stage})}

functions:
  web:
    handler: LambdaEntry.handleWeb
    events:
      - http: ANY {proxy+}
      - http: ANY /
  socket:
    handler: LambdaEntry.handleSocket
    events:
      - websocket: $default
      - websocket: $disconnect

plugins:
  - serverless-layers
  - serverless-plugin-utils

custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"
