service: messaging-api

package:
  individually: true
  exclude:
    - node_modules/**
    - layer/**
    - tools/**
    - "*.md"
    - "*.json"
    - ".git*"

custom:
  env: ${lower(${opt:stage, self:provider.stage})}
  vpcSettings:
    prod:
      securityGroupIds:
        - sg-052314a1eec2f2567
      subnetIds:
        - subnet-01a6b61d749d10c46
    current: ${ternary( ${self:custom.env}, prod, ${self:custom.vpcSettings.prod}, ~ )}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  region: us-east-2
  iam:
    role: arn:aws:iam::428019619026:role/ChurchAppsRole
  environment:
    APP_ENV: ${self:custom.env}
  httpApi:
    binaryMediaTypes:
      - "*/*"

layers:
  dependencies:
    path: layer
    name: ${self:service}-dependencies-${self:custom.env}
    description: Dependencies layer for ${self:service}
    compatibleRuntimes:
      - nodejs20.x
    retain: false

functions:
  web:
    handler: LambdaEntry.handleWeb
    layers:
      - { Ref: DependenciesLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    vpc: ${self:custom.vpcSettings.current}
  socket:
    handler: LambdaEntry.handleSocket
    layers:
      - { Ref: DependenciesLambdaLayer }
    events:
      - websocket: $default
      - websocket: $disconnect
    vpc: ${self:custom.vpcSettings.current}
  timer15Min:
    handler: LambdaEntry.timer15Min
    layers:
      - { Ref: DependenciesLambdaLayer }
    events:
      - schedule: rate(15 minutes)
    vpc: ${self:custom.vpcSettings.current}
  timerMidnight:
    handler: LambdaEntry.timerMidnight
    layers:
      - { Ref: DependenciesLambdaLayer }
    events:
      - schedule: cron(0 5 * * ? *)
    vpc: ${self:custom.vpcSettings.current}

plugins:
  - serverless-plugin-utils
