service: messaging-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  timeout: 10
  region: us-east-2

functions:
  web:
    handler: LambdaEntry.handleWeb
    events:
      - http: ANY {proxy+}
      - http: ANY /
  socket:
    handler: LambdaEntry.handleSocket
    events:
      - websocket: $default
      - websocket: $disconnect

plugins:
  - serverless-layers
  
custom:
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: "lcs-layers"